name: google_ai_dart_sdk_sample
description: "google_ai_dart_sdk_sample"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_hooks: ^0.20.5
  google_generative_ai: ^0.2.0

dev_dependencies:
  pedantic_mono: ^1.25.0

flutter:
  uses-material-design: true
